str(stevens)

library(caTools)

set.seed(3000)
split <- sample.split(stevens$Reverse, SplitRatio = 0.7)
Train <- subset(stevens, split == TRUE)
Test <- subset(stevens, split == FALSE)

install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
StevensTree <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method="class", minbucket=25)
prp(StevensTree)
table(Train$Reverse, Train$LowerCourt)
Predict <- predict(StevensTree, newdata = Test, type = "class")
table(Test$Reverse, Predict)
Accuracy = (44 + 68)/(44 + 33 + 25 + 68)

summary(StevensTree)

library(ROCR)
PredictROCR <- predict(StevensTree, newdata = Test)
PredictROCR
ROCRPred <- prediction(PredictROCR[,2], Test$Reverse)
ROCRPerf <- performance(ROCRPred, "tpr", "fpr")
plot(ROCRPerf)
AUC <- as.numeric(performance(ROCRPred, "auc")@y.values)

StevensTree2 <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method="class", minbucket=5)
prp(StevensTree2)
StevensTree2 <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method="class", minbucket=100)
prp(StevensTree2)

install.packages("randomForest")
library(randomForest)
StevevnsForest <- randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, nodesize = 25, ntree = 200)
Train$Reverse <- as.factor(Train$Reverse)
Test$Reverse <- as.factor(Test$Reverse)
StevevnsForest <- randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, nodesize = 25, ntree = 200)
PredictForest <- predict(StevevnsForest, newdata = Test)
summary(PredictForest)
table(Test$Reverse, PredictForest)
Accuracy = (40 + 78)/(40 + 37 + 15 + 78)

set.seed(100)
StevevnsForest <- randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, nodesize = 25, ntree = 200)
PredictForest <- predict(StevevnsForest, newdata = Test)
summary(PredictForest)
table(Test$Reverse, PredictForest)
Accuracy = (39 + 80)/(40 + 37 + 15 + 78)
set.seed(200)

StevevnsForest <- randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, nodesize = 25, ntree = 200)
PredictForest <- predict(StevevnsForest, newdata = Test)
summary(PredictForest)
table(Test$Reverse, PredictForest)
Accuracy = (37 + 79)/(40 + 37 + 15 + 78)

library(caret)
library(e1071)
library(class)
library(ggplot2)
numFolds <- trainControl(method = "cv", number = 10)
cpGrid <- expand.grid(.cp = seq(0.01, 0.5, 0.01))
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method = "rpart", trControl = numFolds, tuneGrid = cpGrid )

stevensCV <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method = "class", cp = 0.21)
summary(stevensCV)
prp(stevensCV)
predictCV <- predict(stevensCV, newdata = Test, type = "class")
table(Test$Reverse, predictCV)
Accuracy <- (50 + 68)/(50 + 27 + 25 + 68)