#Structure of the data
str(boston)
plot(boston$LON, boston$LAT)

#points works on an existing plot
points(boston$LON[boston$CHAS == 1], boston$LAT[boston$CHAS == 1], pch = 19, col = "blue")
points(boston$LON[boston$TRACT == 3531], boston$LAT[boston$TRACT == 3531], col = "red", pch = 19)
summary(boston$NOX)
points(boston$LON[boston$NOX >= 0.55], boston$LAT[boston$NOX >= 0.55], col = "green", pch = 19)
summary(boston$MEDV)
points(boston$LON[boston$MEDV >= 21.2], boston$LAT[boston$MEDV >= 21.2], col = "blue", pch = 19)
plot(boston$LON, boston$MEDV)
plot(boston$LAT, boston$MEDV)
bostonlm <- lm(MEDV ~ LAT + LON, data = boston)
summary(bostonlm)
plot(boston$LON, boston$LAT)
points(boston$LON[boston$MEDV >= 21.2], boston$LAT[boston$MEDV >= 21.2], col = "blue", pch = 19)
points(boston$LON[bostonlm$fitted.values >=21.2], boston$LAT[bostonlm$fitted.values>=21.2], col = "red", pch = "$")
plot(boston$LON, bostonlm$fitted.values)
plot(boston$LAT, bostonlm$fitted.values)

library(rpart)
library(rpart.plot)
bostonTree <- rpart(MEDV ~ LON + LAT, data = boston)
prp(bostonTree)
plot(boston$LON, boston$LAT)
points(boston$LON[boston$MEDV >= 21.2], boston$LAT[boston$MEDV >= 21.2], col = "blue", pch = 19)
fittedvalues <- predict(bostonTree, data = boston)

points(boston$LON[fittedvalues>= 21.2], boston$LAT[fittedvalues >= 21.2], col = "green", pch = "$")

bostonTree <- rpart(MEDV ~ LON + LAT, data = boston, minbucket = 50)
plot(bostonTree)
text(bostonTree)
plot(boston$LON, boston$LAT)
points(boston$LON[boston$MEDV >= 21.2], boston$LAT[boston$MEDV >= 21.2], col = "blue", pch = 19)
fittedvalues <- predict(bostonTree, data = boston)
points(boston$LON[fittedvalues>= 21.2], boston$LAT[fittedvalues >= 21.2], col = "green", pch = "$")
abline(v=-71.07)
abline(h=42.21)
abline(h=42.17)

set.seed(123)
split <- sample.split(boston$MEDV, SplitRatio = 0.7)
Train <- subset(boston, split == TRUE)
Test <- subset(boston, split == FALSE)

Trainlm <- lm(MEDV ~ LAT + LON + CRIM + ZN + INDUS + CHAS + NOX + RM + AGE + DIS + RAD + TAX + PTRATIO, data = Train)
summary(Trainlm)
linearReg.predict <- predict(Trainlm, newdata = Test)
plot(Test$LON, Test$LAT)
points(Test$LON[Test$MEDV>=21.2], Test$LAT[Test$MEDV>=21.2], col = "blue", pch = 19)
points(Test$LON[linearReg.predict>=21.2], Test$LAT[linearReg.predict>=21.2], col = "green", pch = "*")
linearReg.sse <- sum((linearReg.predict - Test$MEDV)^2)

TrainTree <- rpart(MEDV ~ . - TOWN - TRACT, data = Train)
prp(TrainTree)
predictTest <- predict(TrainTree, newdata = Test)
plot(Test$LON, Test$LAT)
points(Test$LON[Test$MEDV>=21.2], Test$LAT[Test$MEDV>=21.2], col = "blue", pch = 19)
points(Test$LON[predictTest>=21.2], Test$LAT[predictTest>=21.2], col = "red", pch = "$")
TrainTree.sse <- sum((predictTest - Test$MEDV)^2)

library(caret)
library(e1071)
tr.Control <- trainControl(method = "cv", number = 10)
cp.grid <- expand.grid(.cp = seq(0,0.01, 0.001))
tr <- train(MEDV ~ LAT + LON + CRIM + ZN + INDUS + CHAS + NOX + RM + AGE + DIS + RAD + TAX + PTRATIO, data = Train, method = "rpart", trControl = tr.Control, tuneGrid = cp.grid)
tr
bestTree <- tr$finalModel
prp(bestTree)
bestTreePredict <- predict(bestTree, newdata = Test)
plot(Test$LON, Test$LAT)
points(Test$LON[Test$MEDV>=21.2], Test$LAT[Test$MEDV>=21.2], col = "blue", pch = 19)
points(Test$LON[bestTreePredict>=21.2], Test$LAT[bestTreePredict>=21.2], col = "red", pch = "$")
TrainTree.sse <- sum((bestTreePredict - Test$MEDV)^2)

library(randomForest)
TrainForest <- randomForest(MEDV ~ LAT + LON + CRIM + ZN + INDUS + CHAS + NOX + RM + AGE + DIS + RAD + TAX + PTRATIO, data = Train, nodesize = 25, ntree = 200)
PredictForest <- predict(TrainForest, newdata = Test)
plot(Test$LON, Test$LAT)
points(Test$LON[Test$MEDV>=21.2], Test$LAT[Test$MEDV>=21.2], col = "blue", pch = 19)
points(Test$LON[PredictForest>=21.2], Test$LAT[PredictForest>=21.2], col = "red", pch = "$")
TrainTree.sse <- sum((PredictForest - Test$MEDV)^2)